version: '2'

services:

  web:
    build: .
    image: sandbox/aiohttp
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 8000:80
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
